dist: trusty
sudo: true
language: cpp

before_install:
sudo apt-get update
sudo apt install gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - libcurl4-openssl-dev
      - openssl
      - cmake
env:
 - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - gcc --version
  - g++ --version
  - cmake .
  - make